sudo apt-get update
sudo apt-get install -y --force-yes libatlas-base-dev
sudo apt-get install -y --force-yes libopencv-dev
sudo apt-get install -y --force-yes protobuf-compiler
sudo apt-get install -y --force-yes libprotobuf-dev
sudo apt-get install -y --force-yes libgoogle-glog-dev
sudo apt-get install -y --force-yes libgflags-dev
sudo apt-get install -y --force-yes libhdf5-dev
sudo apt-get install -y --force-yes libleveldb-dev
sudo apt-get install -y --force-yes libsnappy-dev
sudo apt-get install -y --force-yes liblmdb-dev
sudo apt-get install -y --force-yes libpython-dev
sudo apt-get install -y --force-yes libboost-python-dev
sudo apt-get install -y --force-yes libboost-filesystem-dev
sudo apt-get install -y --force-yes cython
sudo apt-get install -y --force-yes python-numpy
sudo apt-get install -y --force-yes python-protobuf
sudo apt-get install -y --force-yes python-skimage
sudo apt-get install -y --force-yes python-h5py
sudo apt-get install -y --force-yes python-matplotlib
sudo apt-get install -y --force-yes openjdk-7-jre
